### PR TITLE
Grischuk - Magnus Opera 2021 Game incorrectly tagged as Dubov-Nepo

### PR DESCRIPTION
**Pull request by kutyel**
Somehow this video is wrongly categorized on YouTube as well but this game was played by Magnus and Grischuk as the title says and not Dubov-Nepo which is the previous video...

### CODE REVIEW

**Review by kutyel — COMMENTED** [review]
🤔

**Comment by agadmator-library** [comment]
Changing only names is not enough as entire pgn is incorrect.

**Comment by kutyel** [comment]
Should I add the whole corrected PGN to this PR then? 🤔

**Comment by agadmator-library** [comment]
Go to solution would be to delete all fields from  db/RN732DEw4Gs.json except for `_id` and `videoSnippet`.
There is special solution for cases where description in video is incorrect:
* Players can be overriden in: https://github.com/agadmator-library/agadmator-library.github.io/blob/main/build_scripts/players/playersOverrides.ts
* PGNs can be overriden in: https://github.com/agadmator-library/agadmator-library.github.io/blob/main/build_scripts/pgnOverrides.ts

**Comment by agadmator-library** [comment]
Here is example how override can be made: https://github.com/agadmator-library/agadmator-library.github.io/commit/5446a228b08c2b32fb405fe4baed2971ed55a874

**Comment by kutyel** [comment]
@agadmator-library done, let me know if this worked 👍🏻

**Comment by agadmator-library** [comment]
Lets see :) I'm merging it

**Pull request merged**
